### ISSUE TITLE
windows7下无法运行

### ISSUE THREAD

**Issue by kevin3061** [pangao1990/vue-pywebview-pyinstaller#1]
windows7下无法正常运行，报错，请帮忙看一下
![image](https://user-images.githubusercontent.com/15794385/167972004-3f152aeb-1328-4e39-864d-5b6681389d7a.png)

**Comment by pangao1990** [comment]
你好，根据截图来看，是你的win7系统中启动GUI板块出了问题。可能原因是win7系统中并没有edge浏览器，因此edgechromium ，edgehtml， mshtml 这些客户端引擎也没有。所以无法调用浏览器的webview引擎，自然就无法启动客户端页面了。解决方法就是我在介绍里写的：1，正常模式，那就需要下载安装EdgeWebView2Runtime；2，兼容模式：npm run start:cef 启动。希望可以帮到你

**Comment by kevin3061** [comment]
你好，感谢回复，按照你的建议，安装了EdgeWebView2Runtime，也安装了edge浏览器，错误依旧。采用npm run start:cef 启动也是一样的错误

**Comment by pangao1990** [comment]
我中午的时候更新了下，我发现cef兼容模式下，应该用mainCEF.py，而我用的是main.py，所以我修复了这个。
要不然你下载这个1.0.1版再试试看兼容模式？
<img width="852" alt="image" src="https://user-images.githubusercontent.com/36030293/168029187-e90520af-15b3-41e3-8d06-13d775aeaee4.png">

**Comment by kevin3061** [comment]
你好，已经下载最新版本，并且安装了chrome浏览器，执行npm run start:cef还是报以下错误
![image](https://user-images.githubusercontent.com/15794385/168033147-62e92baa-59f7-41a0-8c6a-9a14cf64bb1a.png)

**Comment by pangao1990** [comment]
你好，是用的python3.8+吗？我晚上找一台win7试试看。我之前只测试过mac和win10，win11，抱歉抱歉

**Comment by kevin3061** [comment]
![image](https://user-images.githubusercontent.com/15794385/168034434-4613e869-a370-40f0-9dc0-45074d11a778.png)
![image](https://user-images.githubusercontent.com/15794385/168034499-a31fecb3-f1bf-4e30-b0e1-f55f3892cfad.png)
![image](https://user-images.githubusercontent.com/15794385/168034569-13e4cfd1-f7f4-477c-8b78-a6f2e7341ddf.png)

**Comment by kevin3061** [comment]
作者，你好，windows7系统可以了吗

**Comment by pangao1990** [comment]
抱歉啊，我没找到win7电脑。我用我媳妇儿的奔腾芯片mac下载了个虚拟机，安装win7系统（我的是M1芯片的mac，压根儿没有M1版本的win7系统）。又安装低版本的python，又安装低版本的node，又配置环境变量。。。焦头烂额。。。兄弟，要不然，你还是升级一下系统吧。win7年代的确有点久远啊，win11界面挺清爽的。我当初测试的win电脑就测试了win10和win11，并没有测试win7，不保证win7可用。

**Comment by kevin3061** [comment]
哎，看来是没办法了，我也不用win7，可客户的电脑系统是win7，也不可能升级。他要做一个客户端，想着用这个脚手架尽快给弄出来，看来只能转战其它方案了

**Comment by pangao1990** [comment]
那如果是这种情况，你试试用你自己的电脑打个包，把生成的exe文件，传到客户win7电脑，也许能运行。因为我试了下用win11电脑打包成exe，然后传到win7电脑，倒是可以运行。

**Comment by kevin3061** [comment]
win11用npm run start，出现空白页面
![image](https://user-images.githubusercontent.com/15794385/168503618-161aa70b-c2db-4aa1-9a61-1170ebf5894b.png)

**Comment by pangao1990** [comment]
根据提示来看，就是没有安装 EdgeWebView2Runtime。不过，因为你这是打算在win7上运行，不如试试用兼容模式

**Comment by kevin3061** [comment]
刚试了一下，win11下cef模式可以正常运行，打包时使用npm run build:cef报错，使用npm run build:folder:cef没问题，然后将打包后的文件夹压缩后放到win10下可以正常运行，但是在win7下还是报错。😭😭😭😭😭
![image](https://user-images.githubusercontent.com/15794385/168504724-9097c24b-ead0-4d0c-8f55-0ed76da00cc7.png)

**Comment by pangao1990** [comment]
那估计还是win7系统支持的不完美，或者你使用的这个win7差点什么东西。。。要不然你试试Eletron？不过，说实话，win7年代是有点久了，就像要兼容IE的感觉一样，有点痛苦

**Comment by kevin3061** [comment]
好的，谢谢，electron太大了，和python交互也不太方便，我试试eel
