### ISSUE TITLE
开发模式下如何看py下打印的日志？

### ISSUE THREAD

**Issue by zzice** [pangao1990/vue-pywebview-pyinstaller#10]
你好，请问开发模式下如何看py下打印的日志？

**Comment by pangao1990** [comment]
@zzice  你好，在开发模式下，可以简单的使用print打印信息，会在终端显示。不过我一般是使用loguru这个py日志模块包，可以选择在终端打印或写入日志文件。当日志文件超过指定大小可以自动分文件备份。总之，非常方便。希望可以帮到你。

**Comment by zzice** [comment]
@pangao1990 谢谢回复，我尝试直接print，未在控制台看到日志，我是用的PyCharm。由于一些其他原因，目前在使用Electron+FastAPI的架构在做桌面应用。
