### ISSUE TITLE
pywebview有参数可以展示地址栏嘛

### ISSUE THREAD

**Issue by zhengjin** [pangao1990/vue-pywebview-pyinstaller#11]
客户有安全要求，需要展示地址栏
有参数可以控制嘛？

**Comment by pangao1990** [comment]
@zhengjin 你好，pywebview本身是用webview加载HTML页面，呈现出客户端的效果。pywebview并不控制展示的部分，展示页面的部分得自己写前端才可以。不过，pywebview有一个函数是 window.get_current_url() ，可以返回当前URL。如果没有加载网址，则返回None。

**Comment by zhengjin** [comment]
感谢
意思是说，没有参数可以像浏览器那样展示出原生地址栏呗？
因为有些web页面，并不是自己开发的
