### ISSUE TITLE
在win7下能正常打开，但是无法显示页面  win764位。

### ISSUE THREAD

**Issue by shanggangyu88** [pangao1990/vue-pywebview-pyinstaller#15]
是不能在win7下运行还是怎么回事？谢谢

**Comment by shanggangyu88** [comment]
使用打包命令是：pnpm run pre:folder:cef

**Comment by pangao1990** [comment]
你好，win7兼容性的确有些问题，win10-win11兼容性好一些。要不然，你试试win10-11系统

**Comment by shanggangyu88** [comment]
客户基本都是 win7 系统。所以要 win7 为主。cef 打包的，打包后运行怎么不是 cef呢？单独使用 pywebview gui 设置为 cef 就可以正常运行发自我的 iPhone在 2023年6月5日，08:40，潘高 ***@***.***> 写道：﻿
你好，win7兼容性的确有些问题，win10-win11兼容性好一些。要不然，你试试win10-11系统
