### ISSUE TITLE
我发现在vue中使用localStorage，软件重启后会被清空，是我的设置问题，还是pywebview的特性？

### ISSUE THREAD

**Issue by galigaligo** [pangao1990/vue-pywebview-pyinstaller#16]

**Comment by pangao1990** [comment]
你好，这是pywebview的问题。我之前也发现无法在vue中使用localStorage持续保存数据，我猜应该是pywebview毕竟没有完整的浏览器内核做支撑，所以这个函数用不了。我的做法是在程序中内置了一个SQLite数据库，将需要持续保存的数据存在数据库中。可以参考api/db/目录下的一些代码示例。
