### ISSUE TITLE
使用命令pnpm run pre和pnpm run build的时候都会报错

### ISSUE THREAD

**Issue by 15259291016** [pangao1990/vue-pywebview-pyinstaller#19]
![image](https://github.com/pangao1990/PPX/assets/87016091/87365ae9-124d-4efc-965a-9e03a8433ac2)

**Comment by 15259291016** [comment]
我好像找到问题了，
![image](https://github.com/pangao1990/PPX/assets/87016091/6da1219e-faf6-4787-a946-ca3970a95f2e)
wo我把 -w去掉就没这个问题了，具体原因不知道，去网上找是说去掉-w

**Comment by pangao1990** [comment]
你好，请问是使用的 [PPX](https://github.com/pangao1990/PPX/) V4.1.0 最新版本吗？

我看你的文件结构，你目前使用的是老版本的框架。使用新的PyInstaller V5.10.1有一些打包参数改变了，所以我在新框架中也随之改变了。另外，新框架也新增了很多新功能。建议你使用新框架，就不会有这方面的问题了。

PPX框架的历史更新记录可以查这里 https://github.com/pangao1990/PPX/releases

**Comment by 15259291016** [comment]
好的谢谢

**Comment by pangao1990** [comment]
> 好的谢谢

不客气呐
