### ISSUE TITLE
主窗口右上角X关闭时，无法直接关闭

### ISSUE THREAD

**Issue by ylwang66** [pangao1990/vue-pywebview-pyinstaller#20]
大佬，我遇到这样的问题。主窗口右上角X关闭时，无法直接关闭；控制台报错如下，而且应用会再次重启一次，控制台进程需要两次才能杀掉，这是什么情况呢？

![image](https://github.com/pangao1990/PPX/assets/32428245/52d99cd6-6013-47ce-88b2-64200b7bca4e)

![image](https://github.com/pangao1990/PPX/assets/32428245/0cd87631-c4c4-4ae0-9d9b-0b0f5a0e2358)

**Comment by pangao1990** [comment]
你好，有两个原因。
A、在开发环境中，需要并行启动前端(vite)和客户端(pywebview)的监听。在mac环境下可以用 & 命令，但是在win的cmd环境下不支持&并行，所以我用了npm-run-all这个模块来支持并行启动前端(vite)和客户端(pywebview)。
B、在开发环境中，为了实现python脚本的热更新功能，我用了nodemon模块。即便客户端点了关闭，nodemon的监听也不会停止，需要在终端中ctrl+c手动关闭nodemon的监听。

原因A导致需要2次才能杀掉；原因B导致主窗口右上角X关闭时，无法直接关闭。

并行监听和热更新都还比较实用，目前一个可行但不优雅的解决办法就是：在开发环境中要关闭客户端，就在终端中ctrl+c

**Comment by cddldg** [comment]
![image](https://github.com/pangao1990/PPX/assets/10046182/3520a4c0-b9b9-4ff8-9e61-f790fd5b9a31)
我这里ctrl+c都没用，程序感觉卡死了，怎么办最好呢

**Comment by pangao1990** [comment]
@wangyulong123  你好，在mac环境下，可以直接在终端中ctrl+c。但是在win环境下，还是会卡死。因此建议开两个cmd终端窗口运行。具体操作请看 #21
