### ISSUE TITLE
![image](https://github.com/pangao1990/PPX/assets/10046182/3520a4c0-b9b9-4ff8-9e61-f790fd5b9a31)

### ISSUE THREAD

**Issue by cddldg** [pangao1990/vue-pywebview-pyinstaller#21]
![image](https://github.com/pangao1990/PPX/assets/10046182/3520a4c0-b9b9-4ff8-9e61-f790fd5b9a31)
我这里ctrl+c都没用，程序感觉卡死了，怎么办最好呢

_Originally posted by @cddldg in https://github.com/pangao1990/PPX/issues/20#issuecomment-1644177235_

**Comment by pangao1990** [comment]
@cddldg 你好，你可以尝试将前端的vite和客户端的pywebview分开启动。

即开两个cmd终端。一个cmd终端运行 `pnpm run dev` ，启动前端的vite；另一个cmd终端运行`pnpm run startos`，启动客户端的pywebview。

这样可以分别使用ctrl+c终止两个cmd终端窗口了。

![iShot_2023-07-21_09 08 43](https://github.com/pangao1990/PPX/assets/36030293/b8f58f27-0532-482f-8337-2447d1e18474)

**Comment by cddldg** [comment]
@pangao1990 好的，感谢，感觉这样不是很优雅！还想请问下，我是用的vscode，要怎么调试呢，打断点都进不了
![image](https://github.com/pangao1990/PPX/assets/10046182/2466f501-f21a-46a6-a159-11fc7f1a32dc)

**Comment by cddldg** [comment]
@pangao1990 在Windows 上找到个方法就是用debug 运行脚本start，关闭窗口以后，可以直接点停止就可了
![image](https://github.com/pangao1990/PPX/assets/10046182/d89aaa9d-1fa9-4df1-b443-a4a809c76534)
