### ISSUE TITLE
icon问题(element-plus)

### ISSUE THREAD

**Issue by cddldg** [pangao1990/vue-pywebview-pyinstaller#23]
app.component(`ele-${key}`, component)
换成
app.component(key, component)

<el-icon><Files /></el-icon>
这样图标才会正常显示

**Comment by pangao1990** [comment]
你好，这里将Element-Plus的Icon组件注册为 `app.component('ele-${key}', component)` ，是为了与第三方图标库作区分。
第三方组件使用 `icon-` 作为前缀，Element官方Icon使用 `ele-` 作为前缀，以免混淆干扰。
<img width="678" alt="iShot_2023-07-21_21 55 28" src="https://github.com/pangao1990/PPX/assets/36030293/5614e951-014e-4355-b116-9b784a83cb3a">

这里，我写的SvgIcon组件可以兼容第三方Icon和Element官方Icon。详情可以查看 `gui/src/components/SvgIcon/index.vue` 组件。

也可以查看相关示例 `gui/src/components/BtnUpdate.vue`
<img width="903" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/2bdc5cd5-9652-4ba5-852f-a0b819a24c7a">

当然了，你那种写法也是对的，Element官方示例就是那么写的。如果你想使用其他第三方图标，也是可以再自己新建组件的。

**Comment by cddldg** [comment]
好的，感谢回单菜鸟提问
