### ISSUE TITLE
使用 pnpm run build:folder打包之后,运行exe 

### ISSUE THREAD

**Issue by 15259291016** [pangao1990/vue-pywebview-pyinstaller#25]
![image](https://github.com/pangao1990/PPX/assets/87016091/a4b99bdd-ec21-446e-b768-58404c71b1e7)

**Comment by 15259291016** [comment]
![image](https://github.com/pangao1990/PPX/assets/87016091/76d2acad-3be2-445b-90ce-32e6ed353f6c)

**Comment by 15259291016** [comment]
不打包，用pycharm运行就正常，调试了半天了，我这菜鸡还是没有解决问题，所以来请教一下

**Comment by 15259291016** [comment]
![image](https://github.com/pangao1990/PPX/assets/87016091/df02b1e1-d27f-4418-b87e-050f843dbdab)
现在项目用的是最早的版本

**Comment by 15259291016** [comment]
是因为我把-w参数去了的问题吗

**Comment by 15259291016** [comment]
找到问题了，原来是我的pywebview是3.6.3，改成4.1.0就没问题了

**Comment by pangao1990** [comment]
兄弟，我建议你还是用PPX V4版本吧，我看你那还是很古老的V1版本，你遇到的一部分问题，在V4版本中都不存在的。
