### ISSUE TITLE
window = webview.create_window url添加成网址报错

### ISSUE THREAD

**Issue by zhangpanzhi** [pangao1990/vue-pywebview-pyinstaller#26]
Exception during dealloc of proxy: Completion handler passed to -[BrowserDelegate webView:didReceiveAuthenticationChallenge:completionHandler:] was not called

**Comment by pangao1990** [comment]
你好，我刚才测试了，仅对 `webview.create_window` 的url参数做改动 `url='https://blog.pangao.vip/docs-ppx/'`，是可以正常显示网站的。我猜测，你那边是不是做了什么其他改动，或者你选的网站是不是有什么限制。

<img width="928" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/871e3631-d561-4f00-8dd0-a6b81b3fb33c">

<img width="988" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/a5b75eef-4da0-4621-9dab-1381bb3fd539">
