### ISSUE TITLE
Error:404 Not Found

### ISSUE THREAD

**Issue by 15259291016** [pangao1990/vue-pywebview-pyinstaller#28]
![image](https://github.com/pangao1990/PPX/assets/87016091/d6f7cd21-e727-4f4d-ae1a-caa1a7cab249)
w我用pycharm启动main.py就成这个样子了

**Comment by pangao1990** [comment]
你可以直接用终端或cmd来启动。我没有用过pycharm，不确定在并行启动前端和后台服务的时候会不会出问题。

**Comment by 15259291016** [comment]
用终端启动没问题

**Comment by 15259291016** [comment]
用pycharm启动main.js会出这个问题

**Comment by 15259291016** [comment]
跟着教程走完，启动main.py文件，会出这个问题

**Comment by 15259291016** [comment]
![image](https://github.com/pangao1990/PPX/assets/87016091/8c4e0b39-8008-4e7d-8622-6049050853eb)

**Comment by pangao1990** [comment]
在 `BtnUpdate.vue` 的 `onCheckUpdate` 函数中，调用 `window.pywebview.api.system_checkNewVersion()` 方法用于检测是否存在新版本。根据你的提供的截图来看，找不到 `window.pywebview.api.system_checkNewVersion()` 方法。

一般来说，如果你clone我的代码，没有改动，直接运行，是不会出现这个问题的。如果你有自己的改动，那可以检查一下是不是把我写的 `system_checkNewVersion()` 方法删掉了。

这个方法我写在 `api/system.py` 文件中，你可以看看这个文件的 `system_checkNewVersion()` 方法还在不在。
<img width="442" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/6e307a25-cb8b-4d29-bcd3-a4c685cfa551">

另外，看看 `api/api.py`文件中，是否引用了 `system`。
<img width="335" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/41c851ca-c425-41c6-b080-d044cf8f0ac1">
