### ISSUE TITLE
How to create a windows and play a video？

### ISSUE THREAD

**Issue by liuhuiCNN** [pangao1990/vue-pywebview-pyinstaller#30]
How to create a windows and play a video？The video is play on a single thread？Is is impossible using PPX？ Thank you！

**Comment by pangao1990** [comment]
你好，这个就是纯前端知识了。可以用`<video />`标签播放视频，如果需要更完善的功能，可以用js在前端写，或者在网上找一些前端开源项目嵌入。
至于要不要单开线程，我觉得如果在看视频的时候没有其他复杂计算，就没必要。跳转其他页面的时候，把视频暂停就可以。在当前页面应该也只有播放视频这一个消耗资源的操作吧。
