### ISSUE TITLE
请问为什么没有使用nuitka代替pyinstaller?

### ISSUE THREAD

**Issue by makerjackie** [pangao1990/vue-pywebview-pyinstaller#34]
听说 nuitka 编译后包体积更小，启动速度更快？

**Comment by pangao1990** [comment]
你好，起初我发现pyinstaller更简单，所以选择了它。后面我会尝试对比nuitka和pyinstaller，感谢反馈。

**Comment by makerjackie** [comment]
请问已经实现了吗，还是 nuitka 无法使用？
