### ISSUE TITLE
更新了migration.sql，数据库没有自动执行相关操作

### ISSUE THREAD

**Issue by WnagoiYy** [pangao1990/vue-pywebview-pyinstaller#36]
没太看懂migration操作的逻辑，是否能直接记录migration.sql的MD5，如果不同则执行migration呢，或者监控sql的每一句(需要去掉所有空白)。

**Comment by pangao1990** [comment]
你好，migration.sql这个文件不需要手动更改。当你手动改变static/db/base.db的数据库结构后(比如新建表，修改表结构等等)，再在项目根目录执行 `m=信息备注 pnpm run alembic` 命令。其中，【信息备注】是用于记录本次修改数据库的具体操作内容。那么，PPX会自动在migration.sql文件中记录本次数据库做了哪些结构修改。当用户安装PPX项目程序时，PPX会检测用户电脑上旧PPX项目的数据库结构是否和新项目数据库的结构相同。不相同则更新数据库结构，但保留数据库数据。如果你的项目中不需要用到本地数据库，或者自定义数据库，那么可以忽略这段代码。
