### ISSUE TITLE
请问为什么我在终端pnpm run start的时候sys.path能正确获取到路径，但是打包成可执行文件后获取到的则是临时文件夹的目录

### ISSUE THREAD

**Issue by Ryuddle** [pangao1990/vue-pywebview-pyinstaller#37]
使用run build打包后生成的exe文件在启动后把所需要的文件在临时文件夹中生成出来，如果使用run build:cef模式的话，会在build文件夹中生成启动所需的文件，这个是我在哪里的配置有问题么

**Comment by Ryuddle** [comment]
使用run build打包后生成的exe文件在启动后把所需要的文件在临时文件夹中生成出来，如果使用run build:cef模式的话，会在build文件夹中生成启动所需的文件，这个是我在哪里的配置有问题么

**Comment by pangao1990** [comment]
你好，其实常规会用到的目录，我都已经在配置文件里面写了对应的变量，直接调用就可以了。

调用方法
```
from pyapp.config.config import Config

print(Config.appDir)
```

<img width="818" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/2312cd46-edc5-4c10-9a29-e78542abbd81">

**Comment by Ryuddle** [comment]
这部分我没有修改，我在页面输出了这一行，这一行是临时文件夹的目录
![M 8_`PXBFSOJ(2@ @{IA)05](https://github.com/pangao1990/PPX/assets/133848117/9d6622d9-9f31-4f25-a33c-b627f4ea9b0c)

**Comment by Ryuddle** [comment]
1.如果我使用pnpm run build 进行构建的话 build 目录里的目录结构是这样的
![image](https://github.com/pangao1990/PPX/assets/133848117/04046599-50ea-497c-a396-13a23b5bf71c)
2.如果我使用pnpm run build:folder 进行构建的话 build 目录的目录结构是这样的
![image](https://github.com/pangao1990/PPX/assets/133848117/c7bbff4e-23ad-4143-ba41-3b859d870158)
使用1生成的exe的话会在临时文件夹中生成需要使用的文件夹，然后导致sys.path输出的路径是临时文件夹。
使用2生成的exe就没有这个问题，因为需要使用到的文件夹在同目录生成了，所以sys.path的输出路径是当前路径

**Comment by pangao1990** [comment]
@Ryuddle  你好，我现在更新PPX到V4.4.0了。
默认使用`pnpm run build`打包时，是使用folder模式打包，而非打包成一个独立的exe。这样就可以解决你遇到的问题（也就是你上面说的【使用2】的情况）。
不仅如此，使用folder模式打包，比打包成一个独立的exe的运行速度要快一些。
当然了，最终还是会打包成一个exe的安装程序的。

<img width="823" alt="image" src="https://github.com/user-attachments/assets/63141869-9771-4720-9878-b2b6bc146851">
