### ISSUE TITLE
请问windows下打包缺少第三方模块，应该怎么弄

### ISSUE THREAD

**Issue by gkyCode** [pangao1990/vue-pywebview-pyinstaller#38]
在api文件夹中引入了openpyxl 

![e1bd5ccd6205dfc262993a0409be7d3](https://github.com/pangao1990/PPX/assets/97236549/240fee2c-689e-4267-bba3-0296f8d2210e)

打包后显示ModuleNotFoundError: No module named 'openpyxl'
![微信图片_20240315160351](https://github.com/pangao1990/PPX/assets/97236549/0966a648-1fdb-4a61-8d99-53896b471d17)

根据一些资料 修改getSpec.py文件
![微信图片_20240315160851](https://github.com/pangao1990/PPX/assets/97236549/169ed740-fc91-4fcc-8058-a36e1b46584d)

依旧打包后报错

**Comment by pangao1990** [comment]
你好，请问，你是用PPX内置的python安装的openpyxl吗？
方式一，直接安装：
```
./pyapp/pyenv/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple openpyxl
```
方式二，初始化安装：
将openpyxl写入requirements.txt文件中，再执行一下初始化 `pnpm run init`

**Comment by gkyCode** [comment]
> 你好，请问，你是用PPX内置的python安装的openpyxl吗？ 方式一，直接安装：
> 
> ```
> ./pyapp/pyenv/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple openpyxl
> ```
> 
> 方式二，初始化安装： 将openpyxl写入requirements.txt文件中，再执行一下初始化 `pnpm run init`

已完美解决 感谢作者大大

**Comment by pangao1990** [comment]
不客气，给个Star支持一下吧，朋友
