### ISSUE TITLE
页面刷新之后报找不到api的错，但是打印又有这个对象

### ISSUE THREAD

**Issue by WnagoiYy** [pangao1990/vue-pywebview-pyinstaller#39]
![image](https://github.com/pangao1990/PPX/assets/16523520/3e1dc59f-1c2e-4a3f-93d4-c0c5f6d9442e)

![image](https://github.com/pangao1990/PPX/assets/16523520/5202a5ec-e52c-406a-b3a7-4b5ed4ba842c)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'api')
放在onMounted里面都不行

**Comment by pangao1990** [comment]
你好，因为在onMounted的时候，python端的函数还不一定挂载在window上了。所以，我在onMounted函数里写了个定时检测，如果window.pywebview已经挂载成功，则执行window.pywebview.api的方法，否则继续定时检测。
可以参考代码 gui/src/components/BtnUpdate.vue 

<img width="553" alt="未命名" src="https://github.com/pangao1990/PPX/assets/36030293/b1aaae3c-b553-4b6f-a0a6-659df0a05c70">

**Comment by WnagoiYy** [comment]
有没有办法设置成：只有挂载了才加载页面呢？

**Comment by WnagoiYy** [comment]
![image](https://github.com/pangao1990/PPX/assets/16523520/6a7fa0f8-56eb-4546-9088-a700e4a2d552)
我直接在main.js搞了一个，好像可以
![2096A1FD](https://github.com/pangao1990/PPX/assets/16523520/56c202a6-a961-47e6-895d-043266a6ccda)

**Comment by pangao1990** [comment]
手动点赞
