### ISSUE TITLE
使用Github Action打包

### ISSUE THREAD

**Issue by geekzsp** [pangao1990/vue-pywebview-pyinstaller#4]
是否考虑使用Github Action，进行不同平台的打包工作？

**Comment by pangao1990** [comment]
你这个点子挺好的。但是非常抱歉，我目前还没有这个计划。

**Comment by pangao1990** [comment]
@geekzsp 你好，V4.0 新版本已经支持基于Github Action 同时打包Windows和macOS安装包了。
