### ISSUE TITLE
有可能使用 pywebview 创建一个异形窗口吗，比如桌宠

### ISSUE THREAD

**Issue by makerjackie** [pangao1990/vue-pywebview-pyinstaller#42]
想要用 python 开发一个桌宠项目，但 pywebview 有可能可以创建异形窗口吗，或者让桌宠之外的背景图 透明？

像这种
![image](https://github.com/pangao1990/PPX/assets/18050469/b10741ff-7329-4c92-981c-d7cc863ad0e2)

**Comment by pangao1990** [comment]
你可以试一下设置 `frameless ` 参数，开启无框窗口。
https://blog.pangao.vip/docs-ppx/api/webview-create-window.html

<img width="812" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/c6a20337-5c6c-4318-9c5a-02593321009b">

**Comment by makerjackie** [comment]
thx!

**Comment by makerjackie** [comment]
你的截图怎么这么好看

**Comment by pangao1990** [comment]
> 你的截图怎么这么好看

我用的是 ishot 截图软件。用了比较多，就这个功能强大，截图美观，你也可以试试看。

<img width="391" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/5396dd4a-ee58-49a1-afd5-9128aea48f96">

**Comment by makerjackie** [comment]
补充： pywebview 有个致命的 bug 导致无法开发 桌宠，在设置 frameless 和 transparent 之后，鼠标将无法点击窗口（会透过窗口点击下面的内容），这是 微软 webview 的问题，已经持续很长时间了，短期看起来不会解决。见 [issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1004)

**Comment by mimi99528** [comment]
你可以使用ctypes.windll.gdi32.CreatePolygonRgn()函数创建多边形窗口，运用算法来描边之类的
