### ISSUE TITLE
建议修改文档加上pyenv环境安装

### ISSUE THREAD

**Issue by allenlzg** [pangao1990/vue-pywebview-pyinstaller#43]
建议修改文档，加上 安装 pyenv 的文档，搞了一下午，python main.py可以运行，用pnpm run start 运行不了，后来发现，电脑没有装pyenv

**Comment by pangao1990** [comment]
你好， 本项目中的pyenv并不是独立模块，不需要单独安装。在执行`pnpm run init`初始化项目时，PPX会自动构建独立的python运行环境，后续安装的python模块都在这个独立环境中，我把它命名为pyenv。

教程的第一步就是初始化项目：
<img width="783" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/f9bf40c1-e6e6-4c32-a89c-90985b5bec26">

**Comment by allenlzg** [comment]
我也不清楚 python新手，两个电脑都是安装了pyenv 后才运行起来的，可能是环境问题
