### ISSUE TITLE
do you have a gui project based on NUXT3. 

### ISSUE THREAD

**Issue by 1211454975** [pangao1990/vue-pywebview-pyinstaller#44]
i create a gui project based on vite, it do well,but i do it based on NUXT3, has some error.PPX cannot support NUXT3?

**Comment by pangao1990** [comment]
你好，理论上来说，无论用哪款前端框架，只要最终是html页面，PPX都是支持的。但是更换其他框架，可能需要做一些适配。

可以看看 main.py 文件，将视图层页面URL改成你项目中能正确打开的地址，试试看。
<img width="729" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/1c80406a-0ab2-4817-b337-1f7237f0b352">

**Comment by 1211454975** [comment]
谢谢！确实如此，需要把端口设置好。nuxt缺省端口是3000
