### ISSUE TITLE
怎么改左上角的图标

### ISSUE THREAD

**Issue by plane55** [pangao1990/vue-pywebview-pyinstaller#45]
![Snipaste_2024-06-15_14-30-15](https://github.com/pangao1990/PPX/assets/41913958/189fc212-3b49-45ea-9ac5-a3e7e3089182)
怎么改左上角的图标

**Comment by pangao1990** [comment]
你好，在 `PPX/pyapp/icon/` 目录下，有四种图片格式，将其全部替换掉，就可以更改图标。

<img width="453" alt="image" src="https://github.com/pangao1990/PPX/assets/36030293/144041a1-cea6-462e-bb0d-acd2fc7f2c56">
