### ISSUE TITLE
点右上角叉叉关闭会报错

### ISSUE THREAD

**Issue by liyu827** [pangao1990/vue-pywebview-pyinstaller#46]
开发时每次关闭就会报错
未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   在 Python.Runtime.ManagedType.TryFreeGCHandle(BorrowedReference reflectedClrObject, BorrowedReference type)
   在 Python.Runtime.Runtime.NullGCHandles(IEnumerable`1 objects)
   在 Python.Runtime.Runtime.TryCollectingGarbage(Int32 runs, Boolean forceBreakLoops)
   在 Python.Runtime.Runtime.Shutdown()
   在 Python.Runtime.PythonEngine.Shutdown()
   在 Python.Runtime.Loader.Shutdown(IntPtr data, Int32 size)
请问巨佬这个是什么原因呢

**Comment by pangao1990** [comment]
是的，在pnpm run start开发模式下，的确是关闭窗口会导致报错，我目前也没找到原因。所以，我一般是在终端控制台ctrl+C终止程序。不过，打包后的程序，关闭窗口并不会导致报错的。 #32
