### ISSUE TITLE
打包后，和调试显示不一致

### ISSUE THREAD

**Issue by zkbaba** [pangao1990/vue-pywebview-pyinstaller#47]
老哥您好：
        我再一次遇到了打包前和打包后，页面显示不一致的问题，
      我使用命令：
              # 正式打包
      pnpm run build
      
显示效果
![image](https://github.com/pangao1990/PPX/assets/51184036/bba51183-50b7-4f48-aa1d-58483f5b3d3d)

左边是调试时候显示的界面，右边是打包后显示的效果，菜单栏就没了，多次尝试打包也没有效果，不知道是什么问题，还请指教！

**Comment by pangao1990** [comment]
你好，你可以尝试用 `python3 -m http.server 8888 --directory /PPX/gui/dist` 开启一个简单的web服务器，浏览器访问 http://localhost:8888/ ，查看你打包之后/PPX/gui/dist/路径下前端网页是否能正常显示。 `--directory`参数后面跟的是你打包之后前端页面所在的目录。
