### ISSUE TITLE
是否有支持linux打包的计划？

### ISSUE THREAD

**Issue by hifong45** [pangao1990/vue-pywebview-pyinstaller#48]
请问，是否有支持linux打包的计划？

**Comment by pangao1990** [comment]
原本没有，我自己没有这个需求。不过既然你提出来了，这个周末我测试一下，把打包linux也加上去

**Comment by Arvin-xc** [comment]
@pangao1990 顺带问下大佬，目前MacOS打包后中Intel和M系列有使用区别吗？ 可以针对M系列和Intel系列单独构建吗？

**Comment by pangao1990** [comment]
@Arvin-xc 
PPX本质上是依赖pyinstaller模块打包。在PPX中的pyapp/spec/getSpec.py脚本，有一个 `target_arch`参数，可供选择的值有`x86_64`，`arm64`，`universal2`。按照pyinstaller官方描述，使用`x86_64`值就是打包成Intel芯片应用，使用`arm64`值就是打包成M芯片应用，使用`universal2`值就是打包成包含M芯片和Intel芯片两套代码的应用。如果使用默认`None`值就是本机电脑是什么芯片就打包成什么。但是这个参数我没有测试过。

我测试过下面的情况：
1、用M芯片电脑打包应用，在Intel芯片电脑上用不了。
2、用Intel芯片电脑打包应用，在M芯片电脑上可以使用。（这也是因为苹果使用Rosetta 2的功劳）
所以，我在github上自动打包的时候使用的是Intel芯片，方便在M芯片或Intel芯片的电脑上都能使用。

**Comment by hifong45** [comment]
现在经常碰到国产化要求，麒麟、统信最常见。还有些特殊行业要求不能B/S，必须C/S。之前用electron，看过Tarui但是需要Rust就暂时旁观。PPX应该算非常非常符合了，期望越来越好

**Comment by hifong45** [comment]
现在经常碰到国产化要求，麒麟、统信最常见。还有些特殊行业要求不能B/S，必须C/S。之前用electron，看过Tarui但是需要Rust就暂时旁观。PPX应该算非常非常符合了，期望越来越好

**Comment by pangao1990** [comment]
@hifong45 你好，PPX 5.0.0 版本已支持Linux打包。（目前仅测试 Ubuntu 22.04.2 版系统）
