### ISSUE TITLE
请教一下，用pyinstaller打包pywebview，提示Invalid file descriptor to ICU data received。

### ISSUE THREAD

**Issue by CodingDjz** [pangao1990/vue-pywebview-pyinstaller#5]
请问知道这个应该如何处理吗。

**Comment by pangao1990** [comment]
你好，我之前也遇到了这个报错提示，是按照这个方法解决的，你可以参考一下。

https://www.cnblogs.com/FHC1994/p/11340940.html?share_token=62a0478b-2781-4cbf-a5f5-f3070236a3b6


解决办法：
1.去cefpython3的github网址上https://github.com/cztomczak/cefpython把源码下载下来，在工程文件夹的 /examples/pyinstaller目录下拷贝 hook-cefpython3.py 文件
![image](https://user-images.githubusercontent.com/36030293/202364162-232752a3-66d5-4266-8437-039940f91fcc.png)

2.把刚复制的hook-cefpython3.py文件粘贴到 /site-packages/PyInstaller/hooks/下（这个要参考自己的PyInstaller安装路径）
![image](https://user-images.githubusercontent.com/36030293/202364208-3e161a46-36f5-4f82-a23e-3454f0c8e507.png)

**Comment by CodingDjz** [comment]
> 你好，我之前也遇到了这个报错提示，是按照这个方法解决的，你可以参考一下。
> 
> https://www.cnblogs.com/FHC1994/p/11340940.html?share_token=62a0478b-2781-4cbf-a5f5-f3070236a3b6
> 
> 解决办法： 1.去cefpython3的github网址上https://github.com/cztomczak/cefpython 把源码下载下来，在工程文件夹的 /examples/pyinstaller目录下拷贝 hook-cefpython3.py 文件 ![image](https://user-images.githubusercontent.com/36030293/202364162-232752a3-66d5-4266-8437-039940f91fcc.png)
> 
> 2.把刚复制的hook-cefpython3.py文件粘贴到 /site-packages/PyInstaller/hooks/下（这个要参考自己的PyInstaller安装路径） ![image](https://user-images.githubusercontent.com/36030293/202364208-3e161a46-36f5-4f82-a23e-3454f0c8e507.png)

好的，十分感谢！我看到这篇文章了，我试了无效~~我再研究研究

**Comment by pangao1990** [comment]
你好，我今天花了一天的时间来研究这个bug。发现这个错误 ICU data 文件指的就是cefpython3缺失icudtl.dat。而这个文件在python3安装的cefpython3模块里就有。Pyinstaller在打包的时候，丢失了。得手动设置将这个文件打包进去，这个bug就解决了。不过，紧接着会有另外一堆类似的bug，都是文件丢失，没有打包进去。我更新了vue-pywebview-pyinstaller程序，你可以再重新下载新版试试看。希望可以帮到你。

对了，我手动打包了如下文件，供你参考：
![image](https://user-images.githubusercontent.com/36030293/206859486-e62a887f-78bf-42de-a644-145c64887861.png)

**Comment by Dxymiemiemie** [comment]
您好，请问图片上的内容是写在.spec 的datas=[]中的吗？
![image](https://user-images.githubusercontent.com/71275391/212480709-fc113018-cc58-4bb7-a835-97df8ee13fa0.png)

@pangao1990

**Comment by pangao1990** [comment]
@Dxymiemiemie 你好，datas一般是打包一些非二进制文件，binaries一般是打包一些二进制文件。因此，我上面提到的一些文件，我都是通过 binaries = [] 打包的。

**Comment by Dxymiemiemie** [comment]
@pangao1990 感谢您的答复，我用了这个办法还是没解决。但是我已经尝试降级pyinstaller为4.1再下载提供的hook-cefpython3就解决了，感觉是pyinstaller5.7版本有些bug，github上提供的hook没有被识别导入。当然也重新创建了个环境。

**Comment by pangao1990** [comment]
@Dxymiemiemie 不客气不客气，你解决了就好。我之前用pyinstaller4的确也是需要重新导入hook-cefpython3，但是后来用pyinstaller5就不需要了。请问你是使用的Python3.8吗？过高或过低版本的Python会有一些包不兼容的问题。

**Comment by baight** [comment]
我也遇到了同样的问题，解决方案如下：
1，找到cefpython3目录。通过pip show cefpython3可找到该目录，如：C:\Users\baight\AppData\Roaming\Python\Python38\site-packages\cefpython3。
2，复制 cefpython3目录下的 icudtl.dat、natives_blob.bin 到 .exe目录下的的 cefpython3 目录里。
3，复制 cefpython3目录下的 所有文件 到 .exe目录里。（经验证，真正需复制的文件是 locales、cef.pak、cef_100_percent.pak、cef_200_percent.pak、cef_extensions.pak、chrome_elf.dll、icudtl.dat、libcef.dll、libEGL.dll、libGLESv2.dll、natives_blob.bin、subprocess.exe、v8_context_snapshot.bin）。

**Comment by lktlktlkt** [comment]
> .spec
你好是添加在哪里的.spec呢
