### ISSUE TITLE
Compile Issue for Python 3.12

### ISSUE THREAD

**Issue by seaskydl** [pangao1990/vue-pywebview-pyinstaller#51]
1. Compiling crash under Python 3.12, issue was raised by package tinyaes, update to version 1.1.0 will solve it.
2.As for pywebview version 5 could not support current api mounting in this project, details will be investigated late, but please be notied that only version under 5 could be support so far.  -- hope auther could help to solve, thanks!

**Comment by pangao1990** [comment]
你好，PPX 5.0.0 版本中，依赖模块升级如下：
tinyaes==1.1.0
pywebview==5.2

**Comment by seaskydl** [comment]
Beutiful!
