### ISSUE TITLE
无法加载本地图片资源

### ISSUE THREAD

**Issue by Chenpeibin** [pangao1990/vue-pywebview-pyinstaller#57]
![image](https://github.com/user-attachments/assets/03af32c1-d2cd-416b-9e74-7b0307e49d5c)
能解决这个问题嘛大佬

**Comment by pangao1990** [comment]
你好，可以先在后端用python将本地图片解析成Base64字符串，再传给前端展示出来。

<img width="767" alt="image" src="https://github.com/user-attachments/assets/f325cd60-c24a-441e-85b7-4ab5a032ed70">
