### ISSUE TITLE
vue的router不支持吗？

### ISSUE THREAD

**Issue by zyunkang** [pangao1990/vue-pywebview-pyinstaller#59]
使用了router，测试正常没问题，但是打包后空白，不使用router，打包可以显示

**Comment by pangao1990** [comment]
你好，可以尝试用 python3 -m http.server 8888 --directory /PPX/gui/dist 开启一个简单的web服务器，浏览器访问 http://localhost:8888/ ，查看打包之后/PPX/gui/dist/路径下前端网页是否能正常显示。 --directory参数后面跟的是打包之后前端页面所在的目录。

又或者是路由中 createWebHashHistory 和 createWebHistory 设置的区别？
