### ISSUE TITLE
打包后执行报错

### ISSUE THREAD

**Issue by Chenpeibin** [pangao1990/vue-pywebview-pyinstaller#61]
![image](https://github.com/user-attachments/assets/d83a0ac5-8880-4091-a916-0743ac7867df)
有大佬知道怎么解决吗？
python添加了mitmproxy这个库之后就会出现这个问题了

**Comment by pangao1990** [comment]
在 pyinstaller 的打包配置文件中，把缺失的文件手动打包进去。有两种方式可以试试：
1、明确知道是缺少哪个dll文件，用 addDll 参数即可。
2、直接将整个 mitmproxy 库打包进去，用 addModules 参数。

https://blog.pangao.vip/docs-ppx/guide/expert/package.html
