### ISSUE TITLE
命令运行没问题，打包后运行就报一下错误，请问一下是什么原因了？

### ISSUE THREAD

**Issue by tz510374699** [pangao1990/vue-pywebview-pyinstaller#8]
![微信截图_20221223114910](https://user-images.githubusercontent.com/16602259/209268066-3258ce6b-82b0-4e76-928e-126b6c5e354b.png)
![微信截图_20221223115317](https://user-images.githubusercontent.com/16602259/209268070-aa4aa46e-7e7a-46d6-978f-ad933b207544.png)
WIN10 WIN7 都运行不起来

**Comment by pangao1990** [comment]
@tz510374699  你好，我也没遇到过这个问题。不过我上网查了下这个报错信息，有网友说是pythonnet的问题。你可以尝试使用python3.8版本再重新运行试试看？

**Comment by pangao1990** [comment]
@tz510374699 你好，我今天一个偶然的机会也出现了这个bug提示信息。经过测试，我发现在win系统下使用了中文路径就会出现这个bug，改为纯英文路径这个报错就不存在了。mac系统下没有这个问题。如果你也是中文路径的问题，可以尝试修改一下。希望可以帮到你。
