### ISSUE TITLE
使用的conda环境安装了webview，npm run start报错

### ISSUE THREAD

**Issue by gwq123456** [pangao1990/vue-pywebview-pyinstaller#9]
![image](https://user-images.githubusercontent.com/52617360/211763300-91689afe-08cd-4d30-a5b5-8d45513bc397.png)
conda 创建了一个python3.8的虚拟环境，安装了pywebview，运行后发现报错。
执行.\pyenv\pyenv\Scripts\pip3.exe list 命令，发现没有webview。
然后执行.\pyenv\pyenv\Scripts\pip3.exe install pywebview==3.7.2，重新安装才好

**Comment by pangao1990** [comment]
@gwq123456 你好，理论上运行 npm run init 就会自动创建python环境，并安装所需的模块。你这个可能是在初始化过程中出了什么问题中断了。不过你后来手动安装了也是可以的。[竖起大拇指]
